FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir \
    --timeout=300 \
    --retries=5 \
    -r requirements.txt

RUN python -c "from sentence_transformers import SentenceTransformer; \
    SentenceTransformer('BAAI/bge-base-en-v1.5')"

RUN python -c "from sentence_transformers import CrossEncoder; \
    CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')"

COPY api/         ./api/
COPY agent/       ./agent/
COPY ingestion/   ./ingestion/
COPY retrieval/   ./retrieval/
COPY evaluation/  ./evaluation/

RUN mkdir -p data/pdfs data/chroma_db

COPY data/chunks.json      ./data/chunks.json


EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]